#easy_admin:
#    entities:
#       - App\Entity\News
easy_admin:
    site_name: Admin Console

    design:
        menu:
            - { route: 'home', label: 'Back to the website', icon: 'home' }
            - { entity: 'User', label: 'User', icon: 'fas fa-users' }
            - { entity: 'News', label: 'News', icon: 'fas fa-newspaper' }
            - { entity: 'Cars', label: 'Cars', icon: 'car' }
            - { entity: 'Marks', label: 'Marks', icon: 'car' }
            - { entity: 'CarBodys', label: 'CarBodys', icon: 'car' }
            - { entity: 'Engines', label: 'Engines', icon: 'car' }
            - { entity: 'EngineTypes', label: 'EngineTypes', icon: 'car' }
            - { entity: 'BlogPosts', label: 'BlogPosts', icon: 'fas fa-comments' }
            - { entity: 'Comments', label: 'Comments', icon: 'fas fa-comments' }

    entities:
        News:
            class: App\Entity\News
            list:
                fields:
                    - title
                    - description
                    - link
                    - { property: 'photo', type: 'image', 'base_path': "/uploads/photos", label: 'Photo' }
                    - { property: 'createdAt', type: 'datetime' }
                    - user
                sort: ['createdAt', 'DESC']
            edit:
                fields:
                    - title
                    - description
                    - link
                    - user
                    #- photo bład wymaga konwertu na string
                    - createdAt
        User:
            class: App\Entity\User
            list:
                fields:
                    - email
                    - roles
                    - password
            edit:
                fields:
                    - email
                    #- password
                    #- { property: 'roles', type: 'checkbox', label: 'roles' }


        Engines:
            class: App\Entity\Engines
        EngineTypes:
            class: App\Entity\EngineTypes
        Cars:
            class: App\Entity\Cars
        Marks:
            class: App\Entity\Marks
        CarBodys:
            class: App\Entity\CarBodys
        BlogPosts:
            class: App\Entity\BlogPosts
        Comments:
            class: App\Entity\Comments
        #User:
        #    class: App\Entity\User

