version: '3.7'

services:
  miedzy-nami-kierowcami-mysql:
    container_name: miedzy-nami-kierowcami-mysql-prod
    ports:
      - '33061:3306'
  miedzy-nami-kierowcami-php:
    container_name: miedzy-nami-kierowcami-php-prod
    environment:
      APP_ENV: prod
      APP_VERSION: prod
      DATABASE_URL: mysql://root:@miedzy-nami-kierowcami-mysql:3306/miedzy-nami-kierowcami_prod

  miedzy-nami-kierowcami-nginx:
    container_name: miedzy-nami-kierowcami-nginx-prod
    ports:
      - '8081:80'
